name: handwriting
channels:
  - pytorch
  - anaconda
  - conda-forge
dependencies:
  - python=3.8
  - pytorch
  - torchvision
  - cudatoolkit
  - tensorboard
  - numpy
  - pandas
  - tqdm
  - matplotlib
  - pytorch-lightning
  - pip
  - pip:
      - pytorch-lightning-bolts