name: handwriting
channels:
  - pytorch
  - anaconda
  - conda-forge
dependencies:
  - python=3.8
  - jupyterlab
  - pytorch
  - torchvision
  - cudatoolkit
  - numpy
  - pandas
  - tqdm
  - matplotlib
  - pip
